[build]
  command = "npx nuxi generate"
  publish = ".output/public"

[build.environment]
  NODE_VERSION = "20"
  BACKEND_URL = ""
  NUXT_PUBLIC_BACKEND_URL = ""

[[redirects]]
  from = "/api/*"
  to = "https://cuddly-wombat-90.loca.lt/api/:splat"
  status = 200
  force = true
