[build]
  command = "npm run build"
  publish = ".output/public"

[build.environment]
  NODE_VERSION = "20"
  NUXT_PUBLIC_BACKEND_URL = "https://mypodbackend2026.loca.lt"

[functions]
  node_bundler = "esbuild"
